name: Laravel Pipeline

on:
  push:
    branches:
      - 10.x

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DB_CONNECTION: mysql
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_DATABASE: ${{ secrets.DB_DATABASE }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      APP_NAME: ${{ secrets.APP_NAME }}
      APP_ENV: ${{ secrets.APP_ENV }}
      APP_KEY: ${{ secrets.APP_KEY }}
      APP_DEBUG: ${{ secrets.APP_DEBUG }}
      APP_URL: ${{ secrets.APP_URL }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Copy code to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            cd /var/www/html
            sudo rm -rf *
            sudo git clone https://github.com/Ahmed-Hodhod/laravel/

            #scp -r . ${{secrets.SERVER_USERNAME}}@${{secrets.SERVER_HOST}}:~/

      - name: Export Environment Variables in the server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            echo "Exporting secrets to .env file..."
            cd /var/www/html/laravel
            echo "DB_CONNECTION=${{ secrets.DB_CONNECTION }}" | sudo tee -a .env
            echo "DB_HOST=${{ secrets.DB_HOST }}" | sudo tee -a .env
            echo "DB_PORT=${{ secrets.DB_PORT }}" | sudo tee -a .env
            echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" | sudo tee -a .env
            echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" | sudo tee -a .env
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" | sudo tee -a .env
            echo "APP_NAME=${{ secrets.APP_NAME }}" | sudo tee -a .env
            echo "APP_ENV=${{ secrets.APP_ENV }}" | sudo tee -a .env
            echo "APP_KEY=${{ secrets.APP_KEY }}" | sudo tee -a .env
            echo "APP_DEBUG=${{ secrets.APP_DEBUG }}" | sudo tee -a .env
            echo "APP_URL=${{ secrets.APP_URL }}" | sudo tee -a .env

      - name: SSH into server and run composer install
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            sudo chown -R www-data:www-data /var/www/html/laravel
            cd /var/www/html/laravel
            sudo a2enmod rewrite
            sudo chown -R www-data storage
            sudo chown -R www-data bootstrap/cache
            composer install 
            sudo systemctl restart apache2
            php artisan migrate --force

            #sudo php artisan serve --host=0.0.0.0 --port=8000 &

# https://codewithsusan.com/notes/deploy-laravel-on-apache
