name: Laravel Pipeline

on:
  push:
    branches:
      - 10.x

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Copy code to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            echo "dummy"
            cd ~/ 
            rm -rf *
            git clone https://github.com/Ahmed-Hodhod/laravel/

            #scp -r . ${{secrets.SERVER_USERNAME}}@${{secrets.SERVER_HOST}}:~/

      - name: SSH into server and run composer install
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            cd ~/laravel
            composer install --no-dev --optimize-autoloader

      - name: Run Artisan Migrate
        run: cd ~/laravel && php artisan migrate --force

      - name: Start Laravel Server
        run: cd ~/laravel && php artisan serve --host=0.0.0.0 --port=8000 &
