name: Laravel Pipeline

on:
  push:
    branches:
      - 10.x
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install PHP and Composer
        run: |
          sudo apt-get update
          sudo apt-get install php php-cli php-mbstring php-xml php-mysql
          sudo php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          sudo php composer-setup.php --install-dir=/usr/local/bin --filename=composer
          sudo composer install

      - name: Run Artisan Migrate
        run: php artisan migrate --force 

      - name: Start Laravel Server
        run: |
          cd ${{ github.workspace }}
          php artisan serve --host=0.0.0.0 --port=8000