name: Laravel Pipeline

on:
  push:
    branches:
      - 10.x

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DB_CONNECTION: mysql
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_DATABASE: ${{ secrets.DB_DATABASE }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      APP_NAME: ${{ secrets.APP_NAME }}
      APP_ENV: ${{ secrets.APP_ENV }}
      APP_KEY: ${{ secrets.APP_KEY }}
      APP_DEBUG: ${{ secrets.APP_DEBUG }}
      APP_URL: ${{ secrets.APP_URL }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Export Environment Variables in the server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            echo "Exporting secrets..."
            echo 'export DB_CONNECTION="${{ secrets.DB_CONNECTION  }}"' | sudo tee -a /etc/bash.bashrc
            echo 'export DB_HOST="${{ secrets.DB_HOST }}"' | sudo tee -a /etc/bash.bashrc
            echo 'export DB_PORT="${{ secrets.DB_PORT }}"' | sudo tee -a /etc/bash.bashrc
            echo 'export DB_DATABASE="${{ secrets.DB_DATABASE }}"' | sudo tee -a /etc/bash.bashrc
            echo 'export DB_USERNAME="${{ secrets.DB_USERNAME }}"' | sudo tee -a /etc/bash.bashrc
            echo 'export DB_PASSWORD="${{ secrets.DB_PASSWORD }}"' | sudo tee -a /etc/bash.bashrc
            echo 'export APP_NAME="${{ secrets.APP_NAME }}"' | sudo tee -a /etc/bash.bashrc
            echo 'export APP_ENV="${{ secrets.APP_ENV }}"' | sudo tee -a /etc/bash.bashrc
            echo 'export APP_KEY="${{ secrets.APP_KEY }}"' | sudo tee -a /etc/bash.bashrc
            echo 'export APP_DEBUG="${{ secrets.APP_DEBUG }}"' | sudo tee -a /etc/bash.bashrc
            echo 'export APP_URL="${{ secrets.APP_URL }}"' | sudo tee -a /etc/bash.bashrc

      - name: Copy code to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            cd /var/www/html
            sudo rm -rf *
            sudo git clone https://github.com/Ahmed-Hodhod/laravel/

            #scp -r . ${{secrets.SERVER_USERNAME}}@${{secrets.SERVER_HOST}}:~/

      - name: SSH into server and run composer install
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            sudo chown -R ubuntu:ubuntu /var/www/html/laravel
            cd /var/www/html
            sudo a2enmod rewrite
            sudo service apache2 restart
            composer install 
            chown -R www-data storage
            chown -R www-data bootstrap/cache
            systemctl restart apache2
            php artisan migrate --force

            #sudo php artisan serve --host=0.0.0.0 --port=8000 &

# https://codewithsusan.com/notes/deploy-laravel-on-apache
