name: Laravel Pipeline

on:
  push:
    branches:
      - 10.x

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DB_CONNECTION: mysql
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_DATABASE: ${{ secrets.DB_DATABASE }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      APP_NAME: ${{ secrets.APP_NAME }}
      APP_ENV: ${{ secrets.APP_ENV }}
      APP_KEY: ${{ secrets.APP_KEY }}
      APP_DEBUG: ${{ secrets.APP_DEBUG }}
      APP_URL: ${{ secrets.APP_URL }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Copy code to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            echo "Exporting secrets..."
            export DB_CONNECTION="${{ secrets.DB_CONNECTION }}"
            export DB_HOST="${{ secrets.DB_HOST }}"
            export DB_PORT="${{ secrets.DB_PORT }}"
            export DB_DATABASE="${{ secrets.DB_DATABASE }}"
            export DB_USERNAME="${{ secrets.DB_USERNAME }}"
            export DB_PASSWORD="${{ secrets.DB_PASSWORD }}"
            export APP_NAME="${{ secrets.APP_NAME }}"
            export APP_ENV="${{ secrets.APP_ENV }}"
            export APP_KEY="${{ secrets.APP_KEY }}"
            export APP_DEBUG="${{ secrets.APP_DEBUG }}"
            export APP_URL="${{ secrets.APP_URL }}"

      - name: Copy code to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            sudo cd /var/www/html
            sudo rm -rf *
            sudo git clone https://github.com/Ahmed-Hodhod/laravel/

            #scp -r . ${{secrets.SERVER_USERNAME}}@${{secrets.SERVER_HOST}}:~/

      - name: SSH into server and run composer install
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            sudo cd /var/www/html
            sudo composer install --no-dev --optimize-autoloader
            sudo php artisan migrate --force

            # Find the PID of the process using the specified port
            PID=$(sudo lsof -t -i :8000)

            # If PID is not empty, kill the process
            if [ -n "$PID" ]; then
                echo "Killing the process using port 8000..."
                sudo kill $PID
            else
                echo "No process found using port 8000."
            fi

            #sudo php artisan serve --host=0.0.0.0 --port=8000 &

# https://codewithsusan.com/notes/deploy-laravel-on-apache
